# jaeger-query-fix.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: jaeger
      component: query
  template:
    metadata:
      labels:
        app: jaeger
        component: query
    spec:
      containers:
      - name: jaeger-query
        image: jaegertracing/all-in-one:1.48  # Same image as Istio's addon
        ports:
        - containerPort: 16686
        env:
        - name: SPAN_STORAGE_TYPE
          value: memory  # In-memory storage for demo
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: istio-system
spec:
  ports:
  - port: 16686
    targetPort: 16686
  selector:
    app: jaeger
    component: query